---
name: Post Chat Message
inputs:
  api-key:
    required: true
  chat-id:
    required: true
  text:
    required: true
runs:
  using: composite
  steps:
    - run: |
        text=$(echo -n "${{ inputs.text }}" | awk '{ printf "%s\\n", $0 }')
        data="{
          \"chat\": \"${{ inputs.chat-id }}\",
          \"text\": \"${text}\"
        }"

        echo "${data}"

        curl \
          -X POST \
          --fail \
          --header "Authorization: Bearer ${{ inputs.api-key }}" \
          --header "Content-Type: application/json" \
          --data-raw "${data}" \
          --verbose \
          https://api.ro.am/v0/chat.post
      shell: bash
